// Generated by CoffeeScript 1.6.2
var DEFAULT_PUBLIC_FOLDER_PATH, DEFAULT_SERVER_PORT, fileServer, http, httpServer, io, nodeStatic, socketIO;

DEFAULT_PUBLIC_FOLDER_PATH = "./public";

DEFAULT_SERVER_PORT = 8000;

http = require("http");

nodeStatic = require("node-static");

socketIO = require("socket.io");

fileServer = new nodeStatic.Server(DEFAULT_PUBLIC_FOLDER_PATH);

httpServer = http.createServer(function(request, response) {
  request.addListener("data", function() {});
  return request.addListener("end", function() {
    return fileServer.serve(request, response);
  });
});

io = socketIO.listen(httpServer);

io.sockets.on('connection', function(socket) {
  socket.emit('message', 'awaiting token');
  return socket.on('message', function(msg) {
    if (msg.length === 6) {
      socket.emit('joining room: ' + msg);
      return socket.join(msg);
    }
  });
});

httpServer.listen(DEFAULT_SERVER_PORT);

console.log('Server running at port: ' + DEFAULT_SERVER_PORT);
